
export const LOCAT_STRAGE_FIELDS = {
    MEMBER: "84JRJFU",
    MEMBER_PERMISSIONS: "H84UHFUR8JU",
    MEMBER_TOKEN: "NFJFUR84HJRI30",
    ACCESS_TOKEN_KEY: "G7kP4sD9Qw2LxR1M",
    DEVICE_ID_KEY: "B8fH2vJ5Nq7ZcT3Y",
    DEVICE_NAME_KEY: "X1rL6mV8Kp3QwS9A"
}